//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnCentralManagement.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP_HOC()
        {
            this.TKB_HOCSINH = new HashSet<TKB_HOCSINH>();
        }
    
        public string ID { get; set; }
        public string TEN_LOP { get; set; }
        public string ID_GIAOVIEN { get; set; }
        public double RATING { get; set; }
        public decimal TIENHOC_COBAN { get; set; }
        public decimal HOC_PHI { get; set; }
        public int MAX_HOCSINH { get; set; }
        public string MA_PHONG { get; set; }
        public int SO_BUOIHOC { get; set; }
        public System.DateTime NGAY_BATDAU { get; set; }
        public System.DateTime NGAY_KETTHUC { get; set; }
        public string ID_TKB { get; set; }
        public int THU2 { get; set; }
        public int THU3 { get; set; }
        public int THU4 { get; set; }
        public int THU5 { get; set; }
        public int THU6 { get; set; }
        public int THU7 { get; set; }
        public int CHUNHAT { get; set; }
        public string MA_CAHOC { get; set; }
    
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
        public virtual TKB_LOP TKB_LOP { get; set; }
        public virtual PHONG_HOC PHONG_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKB_HOCSINH> TKB_HOCSINH { get; set; }
        public virtual CA_HOC CA_HOC { get; set; }
    }
}
