//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnCentralManagement.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHU_HUYNH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHU_HUYNH()
        {
            this.HOC_SINH = new HashSet<HOC_SINH>();
        }
    
        public string ID { get; set; }
        public string PASS_WORD { get; set; }
        public string HO_TEN { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public Nullable<int> GIOI_TINH { get; set; }
        public string DIA_CHI { get; set; }
        public string SO_DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public byte[] AVATAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_SINH> HOC_SINH { get; set; }
    }
}
