//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnCentralManagement.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKB_HOCSINH
    {
        public string ID_HOCSINH { get; set; }
        public string ID_LOP { get; set; }
        public System.DateTime NGAY_HOC { get; set; }
        public Nullable<bool> DI_HOC { get; set; }
        public string LY_DONGHI { get; set; }
    
        public virtual HOC_SINH HOC_SINH { get; set; }
        public virtual LOP_HOC LOP_HOC { get; set; }
    }
}
