//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnCentralManagement.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKB_LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TKB_LOP()
        {
            this.LOP_HOC = new HashSet<LOP_HOC>();
        }
    
        public string ID { get; set; }
        public Nullable<System.DateTime> NGAY_HOC { get; set; }
        public Nullable<bool> DI_DAY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP_HOC> LOP_HOC { get; set; }
    }
}
